export const stopwords = new Set([
  "a", "about", "above", "after", "again", "against", "all", "also", "an",
  "and", "any", "are", "aren", "as", "at", "be", "because", "been", "before",
  "being", "below", "between", "both", "but", "by", "can", "could", "did",
  "didn", "do", "does", "doesn", "doing", "don", "done", "down", "during",
  "each", "even", "every", "few", "for", "from", "further", "get", "gets",
  "getting", "got", "had", "hadn", "has", "hasn", "have", "haven", "having",
  "he", "her", "here", "hers", "herself", "him", "himself", "his", "how",
  "i", "if", "in", "into", "is", "isn", "it", "its", "itself", "just",
  "know", "let", "like", "ll", "look", "make", "me", "might", "more", "most",
  "much", "must", "mustn", "my", "myself", "need", "no", "nor", "not", "now",
  "of", "off", "on", "once", "only", "or", "other", "our", "ours", "ourselves",
  "out", "over", "own", "really", "re", "right", "said", "same", "say", "she",
  "should", "shouldn", "so", "some", "something", "still", "such", "take",
  "tell", "than", "that", "the", "their", "theirs", "them", "themselves",
  "then", "there", "these", "they", "thing", "things", "think", "this",
  "those", "through", "to", "too", "under", "until", "up", "upon", "us",
  "use", "used", "using", "ve", "very", "want", "was", "wasn", "way", "we",
  "well", "were", "weren", "what", "when", "where", "which", "while", "who",
  "whom", "why", "will", "with", "won", "would", "wouldn", "you", "your",
  "yours", "yourself", "yourselves",
  "http", "https", "www", "com", "org", "reddit", "post", "just", "like",
  "what", "this", "that", "with", "have", "from", "they", "been", "will",
  "would", "could", "should", "about", "there", "their", "which", "when",
  "make", "know", "think", "take", "come", "good", "some", "them", "than",
  "other", "into", "over", "also", "back", "still", "here", "then",
  // Generic news/politics noise -- not useful for tech trend detection
  "trump", "biden", "president", "government", "federal", "congress",
  "senate", "house", "republican", "democrat", "election", "vote",
  "political", "politics", "white", "executive", "order", "orders",
  "agencies", "agency", "department", "immediately", "officials",
  "administration", "legislation", "bill", "supreme", "court",
  "announce", "announced", "says", "said", "report", "reports",
  "according", "statement", "decision", "country", "countries",
  "national", "international", "world", "global", "people",
  "years", "year", "today", "yesterday", "week", "month",
  "time", "first", "last", "next", "new", "news",
  "help", "question", "anyone", "does", "work", "working",
  "really", "actually", "pretty", "getting", "going", "trying",
  "want", "need", "best", "better", "much", "many", "most",
  "great", "long", "small", "large", "high", "start", "started",
  "looking", "found", "using", "made", "making", "create", "created",
  "update", "updated", "recently", "since", "already", "finally",
  "seems", "seems", "maybe", "probably", "possible", "sure",
  "free", "paid", "price", "cost", "available", "option", "options",
  "share", "sharing", "check", "point", "issue", "issues",
  "cancel", "stop", "state", "support", "company", "companies",
]);
